### ISSUE TITLE
refactor `createNewProject` functionality in Sherlock for SDK v2

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-cli#13]
**Description**

The `createNewProject` functionality from the sdk v1 has no equivalent in the SDK v2 yet. As its very crucial for Sherlocks adoption and therefore growth, we need a replacement for this functionality.<br><br>**Proposal**

Discuss with @samuel.stroschein if and how there is an replacement for this functionality and then refactor the `createNewProject` functionality

**Comment by samuelstroschein** [comment]
The function exists. `newProject()` but returns you a blob. what it needs is [MESDK-176](https://linear.app/opral/issue/MESDK-176/addunpackfile-to-enable-collaboration-between-dev-tools-web-apps) 

```
const blob = await newProject()
await saveProjectFileAsDirectory(blob)
```
