### ISSUE TITLE
'machine translate' makes network requests even when no translation is required

### ISSUE THREAD

**Issue by jldec** [opral/inlang-cli#2]
### Context
The `inlang machine translate` command makes 1 network call per message to the rpc server (limited to 100 concurrent requests). This happens irrespective of whether translation is required. The progress indicator bar tracks these rpc calls.

The rpc server calls google translate once per language, for those languages which are untranslated.

### Proposal
SInce network requests to the rpc server may be slow, it would be better to filter the calls in the cli (client-side), and only make requests to the rpc server for those messages which require translation.

see [INCLI-1](https://linear.app/opral/issue/INCLI-1/redundant-machine-translations)

**Comment by pboling** [comment]
Knowing now how much network activity is generated by this command I'm going to remove it from my CI and shorthand scripts for format / linting / testing until it is fixed.  I appreciate the transparency!

**Comment by jldec** [comment]
@pboling the latest cli should no longer make network calls for already-translated messages.
